using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;

namespace backend.Controllers
{
    public class BaseController : ControllerBase
    {
        protected string CurrentUserId => User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "";
        protected string UserRole => User.FindFirstValue(ClaimTypes.Role) ?? "";

        protected int CurrentProfileId
        {
            get
            {
                var idClaim = User.FindFirstValue("ProfileId");
                return int.TryParse(idClaim, out int id) ? id : 0;
            }
        }

        /// <summary>
        /// Generates a welcome email HTML template for account setup
        /// </summary>
        protected static string GenerateWelcomeEmailHtml(string fullName, string link, string logoUrl)
        {
            return $"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f3f4f6; margin: 0; padding: 40px 20px;">
    <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);">
        
        <div style="text-align: center; margin-bottom: 30px;">
            <img src="{logoUrl}" alt="MediBook Logo" style="height: 60px; width: auto;">
        </div>

        <h2 style="color: #111827; text-align: center; font-size: 24px; margin-bottom: 20px;">Welcome to MediBook</h2>
        
        <p style="color: #4b5563; font-size: 16px; line-height: 1.6; margin-bottom: 20px;">
            Hello <strong>{fullName}</strong>,
        </p>
        
        <p style="color: #4b5563; font-size: 16px; line-height: 1.6; margin-bottom: 30px;">
            An administrator has created a new account for you on the MediBook platform. To complete your registration and securely access your dashboard, please click the button below to set your password.
        </p>

        <div style="text-align: center; margin-bottom: 30px;">
            <a href="{link}" style="background-color: #0ea5e9; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 16px; display: inline-block; transition: background-color 0.3s;">
                Set Your Password
            </a>
        </div>

        <p style="color: #6b7280; font-size: 14px; line-height: 1.5; margin-bottom: 10px;">
            If the button above does not work, copy and paste the following link into your web browser:
        </p>
        <p style="color: #0ea5e9; font-size: 12px; word-break: break-all; margin-bottom: 40px;">
            {link}
        </p>

        <hr style="border: none; border-top: 1px solid #e5e7eb; margin-bottom: 20px;">

        <p style="color: #9ca3af; font-size: 12px; text-align: center; line-height: 1.5; margin: 0;">
            This is an automated message generated by the MediBook system. <br>
            <strong>Please do not reply to this email.</strong> If you require assistance, contact your clinic administrator directly.
        </p>
        <p style="color: #9ca3af; font-size: 12px; text-align: center; margin-top: 10px;">
            &copy; {DateTime.UtcNow.Year} MediBook Healthcare Systems. All rights reserved.
        </p>
    </div>
</body>
</html>
""";
        }
    }
}