// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311072115_AddDoctorScheduleTable")]
    partial class AddDoctorScheduleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "341743f0-dead-422c-afbf-59f706d72cf6",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7d9b7113-a8f8-4035-99a7-a20dd400f6a3",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = "7d9b7113-a8f8-1767-99a7-a20dd400f6a3",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "02174cf0-9412-4cfe-afbf-59f706d72cf6",
                            RoleId = "341743f0-dead-422c-afbf-59f706d72cf6"
                        },
                        new
                        {
                            UserId = "341743f0-abcd-422c-afbf-59f706d72cf6",
                            RoleId = "7d9b7113-a8f8-4035-99a7-a20dd400f6a3"
                        },
                        new
                        {
                            UserId = "040901f0-abcd-422c-afbf-59f706d72cf6",
                            RoleId = "7d9b7113-a8f8-1767-99a7-a20dd400f6a3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backend.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("DoctorNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("backend.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultationFee = 200m,
                            CreatedAt = new DateTime(2026, 3, 11, 7, 21, 14, 235, DateTimeKind.Utc).AddTicks(8449),
                            DateOfBirth = "",
                            Description = "Specialist in heart diseases with 10 years experience",
                            Email = "sarah.johnson@medibook.com",
                            Experience = "10 years",
                            FullName = "Dr. Sarah Johnson",
                            Gender = "",
                            IsAvailable = true,
                            Phone = "012-3456789",
                            ProfileImageUrl = "",
                            Rating = 4.9000000000000004,
                            ReviewCount = 312,
                            Specialty = "Cardiology",
                            UserId = ""
                        },
                        new
                        {
                            Id = 2,
                            ConsultationFee = 85m,
                            CreatedAt = new DateTime(2026, 3, 11, 7, 21, 14, 235, DateTimeKind.Utc).AddTicks(8491),
                            DateOfBirth = "",
                            Description = "General practitioner with focus on preventive care",
                            Email = "michael.chen@medibook.com",
                            Experience = "15 years",
                            FullName = "Dr. Michael Chen",
                            Gender = "",
                            IsAvailable = true,
                            Phone = "012-9876543",
                            ProfileImageUrl = "",
                            Rating = 4.7999999999999998,
                            ReviewCount = 187,
                            Specialty = "General Practice",
                            UserId = ""
                        },
                        new
                        {
                            Id = 3,
                            ConsultationFee = 150m,
                            CreatedAt = new DateTime(2026, 3, 11, 7, 21, 14, 235, DateTimeKind.Utc).AddTicks(8496),
                            DateOfBirth = "",
                            Description = "Skin specialist with expertise in cosmetic dermatology",
                            Email = "aisha.rahman@medibook.com",
                            Experience = "10 years",
                            FullName = "Dr. Aisha Rahman",
                            Gender = "",
                            IsAvailable = true,
                            Phone = "011-2345678",
                            ProfileImageUrl = "",
                            Rating = 4.7000000000000002,
                            ReviewCount = 156,
                            Specialty = "Dermatology",
                            UserId = ""
                        });
                });

            modelBuilder.Entity("backend.Models.DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 1,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 2,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 3,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 4,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 5,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 6,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 1,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 2,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 3,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 4,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 5,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        });
                });

            modelBuilder.Entity("backend.Models.MedicalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FollowUpDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Medications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalReports");
                });

            modelBuilder.Entity("backend.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalReportUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bukit Jalil, KL",
                            CreatedAt = new DateTime(2026, 3, 11, 7, 21, 14, 233, DateTimeKind.Utc).AddTicks(5878),
                            DateOfBirth = "1998-09-24",
                            Email = "patient@2.com",
                            FullName = "Petient 1",
                            Gender = "Female",
                            MedicalReportUrl = "",
                            Phone = "012-3456789",
                            UserId = "341743f0-abcd-422c-afbf-59f706d72cf6"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "02174cf0-9412-4cfe-afbf-59f706d72cf6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "198171c2-0f0d-43b6-852d-b818d98470e8",
                            CreatedAt = new DateTime(2026, 3, 11, 7, 21, 13, 938, DateTimeKind.Utc).AddTicks(6551),
                            Email = "admin@2.com",
                            EmailConfirmed = true,
                            FullName = "Admin 1",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@2.COM",
                            NormalizedUserName = "ADMIN@2.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFrVX3mnByY2ZOFGAt3SSbypb2xiW7ovWvuZ3/G3MeCYJXOwq0UUQDvy2dO6AplsZw==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "445bca3f-51b1-46a8-89ed-34acb80dd7eb",
                            TwoFactorEnabled = false,
                            UserName = "admin@2.com"
                        },
                        new
                        {
                            Id = "341743f0-abcd-422c-afbf-59f706d72cf6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b628e80b-d168-4fab-ad48-ee5840c075a6",
                            CreatedAt = new DateTime(2026, 3, 11, 7, 21, 14, 37, DateTimeKind.Utc).AddTicks(2965),
                            Email = "patient@2.com",
                            EmailConfirmed = true,
                            FullName = "Patient 1",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@2.COM",
                            NormalizedUserName = "PATIENT@2.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECG8Ozdj4ddnd6nGYPJAy6zkGtmQcjv/mp9enDM3BF8ohmTNMAgJ10YtmoBq/qY5oQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Patient",
                            SecurityStamp = "71a43e9c-d7e9-4197-9db4-5abd16d76470",
                            TwoFactorEnabled = false,
                            UserName = "patient@2.com"
                        },
                        new
                        {
                            Id = "040901f0-abcd-422c-afbf-59f706d72cf6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "267bf17c-aa2f-414d-94b4-950da68eb320",
                            CreatedAt = new DateTime(2026, 3, 11, 7, 21, 14, 134, DateTimeKind.Utc).AddTicks(5077),
                            Email = "doctor@2.com",
                            EmailConfirmed = true,
                            FullName = "Doctor 1",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR@2.COM",
                            NormalizedUserName = "DOCTOR@2.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOE6+PpCW806wIcLIJi5/HOhSHntWy0r8B80+GPihxFJdRukUWcSiZ15ylnhwMecBw==",
                            PhoneNumberConfirmed = false,
                            Role = "Doctor",
                            SecurityStamp = "8c28fe9f-63da-4133-b964-7067553b4a1f",
                            TwoFactorEnabled = false,
                            UserName = "doctor@2.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Appointment", b =>
                {
                    b.HasOne("backend.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Models.DoctorSchedule", b =>
                {
                    b.HasOne("backend.Models.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("backend.Models.MedicalReport", b =>
                {
                    b.HasOne("backend.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("backend.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
