// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401111228_AddDoctorLeaveDates")]
    partial class AddDoctorLeaveDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BreakEnd")
                        .HasColumnType("text");

                    b.Property<string>("BreakStart")
                        .HasColumnType("text");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5,
                            DoctorId = 1,
                            EndTime = "17:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "09:00"
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 1,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 2,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 3,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 4,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 5,
                            DoctorId = 2,
                            EndTime = "16:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "08:00"
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 1,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 2,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 3,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 4,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 5,
                            DoctorId = 3,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 1,
                            DoctorId = 4,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 2,
                            DoctorId = 4,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 3,
                            DoctorId = 4,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = 4,
                            DoctorId = 4,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = 5,
                            DoctorId = 4,
                            EndTime = "18:00",
                            IsActive = true,
                            SlotDurationMinutes = 30,
                            StartTime = "10:00"
                        });
                });

            modelBuilder.Entity("HealthQuestionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentMedications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("SeverityLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SymptomDuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("HealthQuestionnaires");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "341743f0-dead-422c-afbf-59f706d72cf6",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7d9b7113-a8f8-4035-99a7-a20dd400f6a3",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = "7d9b7113-a8f8-1767-99a7-a20dd400f6a3",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "02174cf0-9412-4cfe-afbf-59f706d72cf6",
                            RoleId = "341743f0-dead-422c-afbf-59f706d72cf6"
                        },
                        new
                        {
                            UserId = "341743f0-abcd-422c-afbf-59f706d72cf6",
                            RoleId = "7d9b7113-a8f8-4035-99a7-a20dd400f6a3"
                        },
                        new
                        {
                            UserId = "040901f0-abcd-422c-afbf-59f706d72cf6",
                            RoleId = "7d9b7113-a8f8-1767-99a7-a20dd400f6a3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ReportAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AbnormalFindings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MedicalReportId")
                        .HasColumnType("integer");

                    b.Property<string>("NormalFindings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalReportId")
                        .IsUnique();

                    b.ToTable("ReportAnalyses");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("backend.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("DoctorNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("backend.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<DateTime>>("LeaveDates")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone[]");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qualifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultationFee = 200m,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1120),
                            DateOfBirth = "",
                            Description = "Specialist in heart diseases with 10 years experience",
                            Email = "sarah.johnson@medibook.com",
                            Experience = "10 years",
                            FullName = "Dr. Sarah Johnson",
                            Gender = "",
                            IsAvailable = true,
                            Languages = "",
                            LeaveDates = new List<DateTime>(),
                            Phone = "012-3456789",
                            ProfileImageUrl = "",
                            Qualifications = "",
                            Rating = 4.9000000000000004,
                            ReviewCount = 312,
                            SpecialtyId = 1,
                            UserId = ""
                        },
                        new
                        {
                            Id = 2,
                            ConsultationFee = 85m,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1130),
                            DateOfBirth = "",
                            Description = "General practitioner with focus on preventive care",
                            Email = "michael.chen@medibook.com",
                            Experience = "15 years",
                            FullName = "Dr. Michael Chen",
                            Gender = "",
                            IsAvailable = true,
                            Languages = "",
                            LeaveDates = new List<DateTime>(),
                            Phone = "012-9876543",
                            ProfileImageUrl = "",
                            Qualifications = "",
                            Rating = 4.7999999999999998,
                            ReviewCount = 187,
                            SpecialtyId = 5,
                            UserId = ""
                        },
                        new
                        {
                            Id = 3,
                            ConsultationFee = 150m,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1130),
                            DateOfBirth = "",
                            Description = "Skin specialist with expertise in cosmetic dermatology",
                            Email = "aisha.rahman@medibook.com",
                            Experience = "10 years",
                            FullName = "Dr. Aisha Rahman",
                            Gender = "",
                            IsAvailable = true,
                            Languages = "",
                            LeaveDates = new List<DateTime>(),
                            Phone = "011-2345678",
                            ProfileImageUrl = "",
                            Qualifications = "",
                            Rating = 4.7000000000000002,
                            ReviewCount = 156,
                            SpecialtyId = 2,
                            UserId = ""
                        },
                        new
                        {
                            Id = 4,
                            ConsultationFee = 50m,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1130),
                            DateOfBirth = "",
                            Description = "Demo doctor account.",
                            Email = "doctor@2.com",
                            Experience = "1 year",
                            FullName = "Doctor 1",
                            Gender = "",
                            IsAvailable = true,
                            Languages = "",
                            LeaveDates = new List<DateTime>(),
                            Phone = "011-9999999",
                            ProfileImageUrl = "",
                            Qualifications = "",
                            Rating = 0.0,
                            ReviewCount = 0,
                            SpecialtyId = 5,
                            UserId = "040901f0-abcd-422c-afbf-59f706d72cf6"
                        });
                });

            modelBuilder.Entity("backend.Models.MedicalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FollowUpDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Medications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UploadedByRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalReports");
                });

            modelBuilder.Entity("backend.Models.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("backend.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalReportUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bukit Jalil, KL",
                            Allergies = "",
                            BloodType = "",
                            ChronicConditions = "",
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 773, DateTimeKind.Utc).AddTicks(4700),
                            DateOfBirth = "1998-09-24",
                            Email = "patient@2.com",
                            EmergencyContactName = "",
                            EmergencyContactPhone = "",
                            FullName = "Patient 1",
                            Gender = "Female",
                            MedicalReportUrl = "",
                            Phone = "012-3456789",
                            UserId = "341743f0-abcd-422c-afbf-59f706d72cf6"
                        });
                });

            modelBuilder.Entity("backend.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1040),
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1040),
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1050),
                            Name = "Endocrinology"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1050),
                            Name = "Gastroenterology"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1050),
                            Name = "General Practice"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1050),
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1050),
                            Name = "Obstetrics & Gynecology"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1080),
                            Name = "Oncology"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1080),
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1090),
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1090),
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1090),
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1090),
                            Name = "Pulmonology"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1090),
                            Name = "Radiology"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1090),
                            Name = "Surgery"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 774, DateTimeKind.Utc).AddTicks(1090),
                            Name = "Urology"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "02174cf0-9412-4cfe-afbf-59f706d72cf6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ac59873-b399-4fe5-ad73-482ecc91089c",
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 656, DateTimeKind.Utc).AddTicks(6210),
                            Email = "admin@2.com",
                            EmailConfirmed = true,
                            FullName = "Admin 1",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@2.COM",
                            NormalizedUserName = "ADMIN@2.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOtbQZkMo8xOA3rgkbxPFOtg1l2rPA3LOB1tJFEG+C29uRndBAcP5iQLWY3o+cQf/w==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "34f654a0-7755-437d-8c80-a707fe762904",
                            TwoFactorEnabled = false,
                            UserName = "admin@2.com"
                        },
                        new
                        {
                            Id = "341743f0-abcd-422c-afbf-59f706d72cf6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ed70c71b-5810-4ca1-80f2-3058d55717ef",
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 695, DateTimeKind.Utc).AddTicks(6060),
                            Email = "patient@2.com",
                            EmailConfirmed = true,
                            FullName = "Patient 1",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@2.COM",
                            NormalizedUserName = "PATIENT@2.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJhsUwVCKvtD0NeDWA0B6PsAmBMKdgL29dPiNFnP0a98QddenKIO0/pwgnWCp+L7IQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Patient",
                            SecurityStamp = "7baaa677-7b94-4d93-a9e9-c85f6548aa57",
                            TwoFactorEnabled = false,
                            UserName = "patient@2.com"
                        },
                        new
                        {
                            Id = "040901f0-abcd-422c-afbf-59f706d72cf6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d0ba512-b627-45d2-82c5-6ca1eddb9d6d",
                            CreatedAt = new DateTime(2026, 4, 1, 11, 12, 27, 735, DateTimeKind.Utc).AddTicks(6990),
                            Email = "doctor@2.com",
                            EmailConfirmed = true,
                            FullName = "Doctor 1",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR@2.COM",
                            NormalizedUserName = "DOCTOR@2.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM8sTNWtgT0JOySViRYb4UJYxq0ROyQvV4BjfWndMikQmoYMV2JC93Ct9lqAKbH/bQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Doctor",
                            SecurityStamp = "ac8f4e9a-9320-437e-a87a-b15bc53f73af",
                            TwoFactorEnabled = false,
                            UserName = "doctor@2.com"
                        });
                });

            modelBuilder.Entity("DoctorSchedule", b =>
                {
                    b.HasOne("backend.Models.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HealthQuestionnaire", b =>
                {
                    b.HasOne("backend.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReportAnalysis", b =>
                {
                    b.HasOne("backend.Models.MedicalReport", "MedicalReport")
                        .WithOne()
                        .HasForeignKey("ReportAnalysis", "MedicalReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalReport");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.HasOne("backend.Models.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("Review", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Models.Appointment", b =>
                {
                    b.HasOne("backend.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Models.Doctor", b =>
                {
                    b.HasOne("backend.Models.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("backend.Models.MedicalReport", b =>
                {
                    b.HasOne("backend.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany("MedicalReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("backend.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalReports");
                });

            modelBuilder.Entity("backend.Models.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
